### ISSUE TITLE
Provide with sample chats

### ISSUE THREAD

**Issue by lucasrodes** [lucasrodes/whatstk#11]
Provide with some sample chats so that the user can test the project on a fake chat. 

In addition, this chat should be used as the standard file when comparing results between users or simply for debugging purposes.

**Comment by jeiros** [comment]
Do you guys mind if I use your sample chat, I am working on something like this myself and would need one too for debugging and such (and for not uploading my private conversations to GitHub). 

Cheers and good work!

**Comment by lucasrodes** [comment]
Hi @jeiros, feel free to use our sample chat. However, I am afraid that it is very simple and short. In this regard, for the future we had thought to generate a more complex and long chat using some kind of machine learning approach.

Looking forward to seeing your results ;)!

**Comment by lucasrodes** [comment]
Closed due to inactivity
