### ISSUE TITLE
Automate chat text files to CSV conversion

### ISSUE THREAD

**Issue by matcrowley** [lucasrodes/whatstk#113]
Hi, 
I'm looking to import txt whatsapp chats from a folder into Python without specifying what the txt file names will be. 
In essence, I want to be able to run it in a way that is irrespective of the files that are in the folder, it just picks up whatever txt files are in that folder (for example they might be changing in number and changing daily). I was wondering if there is a way to do this and still leverage the whatstk library to clean the data from all files and then export it as one to csv?
Thanks, 
Matt

**Comment by lucasrodes** [comment]
Hi @matcrowley,
Thanks for your interest in this library. Let me know if the code below helps you out.

Just to verify, could you check your `whatstk` version? You can do this by running the following
```
$ python -c "import whatstk; print(whatstk.__version__)"
```

I've tested the code below with version >=0.4.0.

---
### Sample code
Let's suppose we have a folder named `input` with a bunch of files

```txt
input/
 ├── chat_1.txt
 ├── chat_2.txt
  ...
 └── chat_n.txt
```

and that we want to convert them to CSV and place them in a folder named `output/ `.

You can use  the following:

```python
from whatstk import WhatsAppChat
from glob import glob
import os


# Define input and output folder
input_folder = "input"
output_folder = "output"

# Get paths to input files (txt)
input_files = glob(os.path.join(input_folder, "*.txt"))

# Iterate over input files and export
for filename in input_files:
    print(f"Exporting {filename}")
    # Load chat
    chat = WhatsAppChat.from_source(filename)
    # Define output filename
    filename_new = filename.split("/")[1].replace("txt", "csv")
    # Export
    chat.df.to_csv(os.path.join(output_folder, filename_new), index=False)
```

Note: In upcoming version 0.4.1, you may substitute the last line above for 

```python
chat.to_csv(os.path.join(output_folder, filename_new))
```

**Comment by matcrowley** [comment]
Thanks very much @lucasrodes, this worked great! 
Just a couple of quick follow up questions. 
What might this look like if:
1. I was looking to export everything onto a single csv file? 
2. And secondly, if I was looking to pull the txt files from a Google Drive folder? (unsure if this is possible or not) 
Thanks!

**Comment by lucasrodes** [comment]
Hi @matcrowley,
On your questions:

> 1. I was looking to export everything onto a single csv file?
You could do multiple things. I'd recommend using library [`from_sources`](https://whatstk.readthedocs.io/en/stable/source/code_examples/load_chat_multiple.html) method to load from multiple files and merge these into one object. Use the code above, and substitute for loop for:

```python
from whatstk import WhatsAppChat
from glob import glob
import os


# Define input and output folder
input_folder = "input"
output_single_filename = "output.csv"

# Get paths to input files (txt)
input_files = glob(os.path.join(input_folder, "*.txt"))

# Load all txt into a single object
chat = WhatsAppChat.from_sources(input_files)
# Export
chat.df.to_csv(output_single_filename, index=False)

You could potentially sort by date before exporting, adding the following line after first line:

```python
chat.df = chat.df.sort_values("date") 
```

> 2. And secondly, if I was looking to import the `txt` files from a Google Drive folder? (unsure if this is possible or not)
Currently, there is no support for direct loading from Google Drive, may add this in the future. For now, you'd either:

- Manually download all files from Google Drive prior to running `whatstk`
- Use some Python client to automate the download. See some resources: [Google official CLI](https://developers.google.com/drive/api/v3/quickstart/python), [PyDrive](https://github.com/googleworkspace/PyDrive).

Support may be added in the future.


---

Consider closing and opening new issues, to keep threads clean. So for instance, for each new question, I'd suggest that you may open a new issue. And once you get a response, feel free to close the issue.

Thanks!

**Comment by matcrowley** [comment]
Thanks @lucasrodes, much appreciated. 
Regarding 1. above that seems to work, however the consolidated csv appears to only have the latest 4 messages from the second txt file (I just tried this with two txt files for now).  Not too sure on the reason for that or if there might be a limit?
Regarding 2. above, thanks for your suggestions and understood. 
Many thanks

**Comment by lucasrodes** [comment]
Hi @matcrowley,
What is happening in 1 is likely due to the fact that when loading from multiple sources, the chats are merged based on date, so messages with the same date might be discarded. This is actually intended to easily merge text files from the same chat. Please take a look at the [documentation](https://whatstk.readthedocs.io/en/stable/source/code_examples/load_chat_multiple.html).

Therefore for your purpose, you may simply use `pandas instead`.


```python
from whatstk import WhatsAppChat
import panda as pd
from glob import glob
import os


# Define input and output folder
input_folder = "input"
output_single_filename = "output.csv"

# Get paths to input files (txt)
input_files = glob(os.path.join(input_folder, "*.txt"))

# Load all chats. Place them in a list of dataframes
chats = [WhatsAppChat.from_source(filename).df for filename in input_files]
df_all_chats = pd.concat(chats)
df_all_chats.to_csv(output_single_filename, index=False)
```

For more info, please check the Pandas documentation: https://pandas.pydata.org/docs/reference/api/pandas.concat.html

**Comment by lucasrodes** [comment]
@matcrowley 
Last version (v0.5.0) of the library now supports GDrive links.

Install it via 
```
pip indtall whatstk
```
