### ISSUE TITLE
Chat Parser Not Working

### ISSUE THREAD

**Issue by mennahass** [lucasrodes/whatstk#135]
I am trying to use WhatsAppChat module of whatstk but it is no longer working. It used to work before June but apparently an update happened to whatsapp and it is no longer working.

I use it like this: "chat = WhatsAppChat.from_source(filepath="/content/_chat.txt")"

I get this error: Header automatic extraction failed. Please specify the format manually by setting input argument `hformat`. Report this issue so that automatic header detection support for your header format is added: https://github.com/lucasrodes/whatstk/issues.

**Comment by lucasrodes** [comment]
Thanks for reporting, @mennahass !

Could you share a snippet of your `_chat.txt` file (replace personal messages with arbitrary text), please?

I am interested in seeing the format of the chat file and see if I can reproduce the error.

Thanks!

**Comment by mennahass** [comment]
Here's a snippet:
[28/02/2022, 9:52:58 PM] ملتقي: ‎Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them.
[28/02/2022, 9:52:58 PM] ~ AK: ‎~ AK created this group
[17/01/2023, 10:14:01 AM] ملتقي: ‎You joined using this group's invite link
[17/01/2023, 10:14:09 AM] ~ عماد عافيه: 12
[17/01/2023, 10:14:37 AM] ~ عماد عافيه: لتر0 3
[17/01/2023, 10:14:48 AM] ~ عماد عافيه: لتر ونص40

The same file used to work around May 15th. But I keep exporting whatsapp chats to get updates to the chat. Is this happening because of a whatsapp update?

**Comment by mennahass** [comment]
I think I found where the bug is, the following message is the one that is producing the error:

[23/05/2023, 6:03:31 PM] ~ سبحان الله وبحمده سبحان الله العظيم: إلى جميع المواطنين. ﺻﺪﺭ ﻋﻦ وزاره الداخليه المصريهﺍﻟﺒﻴﺎﻥ ﺍﻟﺘﺎﻟﻲ:
ﻓﻲ ﻇﻞ ﺍﻟﻈﺮﻭﻑ ﺍﻟﺤﺮﺟﺔ ﺍﻟﺘﻲ ﺗﻤﺮ ﺑﻬﺎ ﺍﻟﺒﻼ‌ﺩ ، ﻧﺤﻴﻂ ﺍﻫﻠﻨﺎ ﺍﻟﻜﺮﺍﻡ ﺑﻀﺮﻭﺭﺓ ﺍﺧﺬ ﺍﻟﺤﻴﻄﺔ ﻭﺍﻟﺤﺬﺭ ﺧﺼﻮﺻﺎ ﻓﻲ ﻣﻨﺎﺯﻟﻬﻢ ﻣﻦ ﻧﺎﺣﻴﺔ ﻗﻔﻞ ﺍﻷﺑﻮﺍﺏ ﺟﻴﺪﺍ ﻭﻋﺪﻡ ﺍلتعاطف مع ﺄﻱ شخص ﻻ تعرفه ﺗﻔﺎﺩﻳﺎ ﻷﻱ ﺧﻠﻞ ﻳﺬﻛﺮ ، وعدم إستعمال المصعد مع شخص غريب وعدم صعود الدرج ليلا" دون إعلام احد من اهل المنزل حفاظا" على سلامتكم. يرجى الإلتزام بالتعليمات لأجل سلامتكم
خبــــرعـــــــــــــــاجل
3 أو 4 رجال قد يأتوا الى منزلك مدعين أنهم من شركة المياه، وقد يزعمون أنهم من اسكوم لتغيير المصابيح الكهربائية مجانا! وقد رصدوا في عدة أماكن. 
لا تدعوهم يدخلوا بيوتكم. هم لصوص لسرقة ألاموال والأولاد تحت تهديد السلاح. 
تنبيه ارسلها لجميع جهات الاتصال الخاصة بك، لأنك قد تنقذ حياة انسان. 
وتأكد من جعل جميع الأبواب مغلقة و موصودة في جميع الأوقات.
اكدو على الشغالات والاطفال محدش يفتح الباب من غير مايقول مين وايه اسمه. والله يحمينا ويحفظنا من كل سوء
عـــــــااااجـــــــــل
اللواء / مجدي عبدالغفار وزارة الداخلية .
الخبر اكيد واحذروا من اي غريب تتعاملوا معاه في هذه الايام. ، وعليه ﺇﻗﺘﻀﻰ ﺍﻟﺘﻨﺒﻴﻪ.
: تحذيرمهم
مهم مهم مهم مهم مهم مهم مهم مهم مهم مهم مهم مهم مهم مهم مهم مهم مهم مهم مهم مهم مهم مهم مهم مهم مهم مهم مهم مهم مهم جدآجدآجدآ
تحذيرمهم
......مشعوذو القرن ٢١......
la e-sorcellerie
السحرة و المشعوذين بدؤوا بطرق جديدة للإبتزاز وهي كالآتي :
يقومون بإضافة رقمك على الواتساب ويشاهد صورة العرض اذا كنت مثبت صورة إبنك أو بنتك فيقوم بحفظها لديه وبعدها يقوم بتهديدك بالصورة بتحويل المبلغ المطلوب له أو يقوم بسحر طفلك...!!!
☝لااااا أحد يحط صور لأطفاله..
كل شخص قام بوضع صور أولاده الصغار على الواتساب يغيرها..
📲 أرسلها لغيرك.......
اللهـــــــــــــــم أجعل كيدهم في نحورهم...
عاااااجـــــــــــــل . . . . .
لا أحد يرد على المكالمات الواردة من الارقام التالية :
0025270600930
0025270600931
0025270600932
0025270600933
0025270601000
00212692298652
الرقم الأخير مغربي....
وهذا الرقْم تجيك منه رسالة مكتوب فيها (اتصل بي ضروري)....
جميع اﻷرقام في اﻷعلى (هكر) بيهكروا تلفونك وبسحبو الرصيد فور فتح الخط وياخذو جميع الصور والفيديوهات...!!
📲 الرجــــاااء النشر...
خبــرـرـر عاااااجـــــل :
سوف يجيك رابط ومكتوب عليه (أطفال وبنات سوريا تحت التعذيـــــــــب)
هذا رابط لو فتحت عليه انسحب كل اللي بجوالك له من صــور واســماء ورسائــل وفيديــو...
اللــــــــــــــه لا يسامح من قراها ولا يرسلها إذا انت جتك المعلومة....!!

The entire chat before and after this message works. 

When I tried limiting this message to the following and adding another message, it worked:
[23/05/2023, 6:03:31 PM] ~ سبحان الله وبحمده سبحان الله العظيم: إلى جميع المواطنين ﺻﺪﺭ ﻋﻦ  وزاره الداخليه المصريهﺍﻟﺒﻴﺎﻥ ﺍﻟﺘﺎﻟﻲ
[22/05/2023, 2:56:39 PM] ~ ربي ابعد عني الحاقدين: لوبعتها 8ج اتلام 8ج البكته

When I tried using the abridged version of the problematic message on its own, it produced the same error:
[23/05/2023, 6:03:31 PM] ~ سبحان الله وبحمده سبحان الله العظيم: إلى جميع المواطنين ﺻﺪﺭ ﻋﻦ  وزاره الداخليه المصريهﺍﻟﺒﻴﺎﻥ ﺍﻟﺘﺎﻟﻲ

**Comment by lucasrodes** [comment]
Hi @mennahass,
Sorry for my belated response.

I am now trying to work out a solution for this.

If I only use the last part of the text:

```
[23/05/2023, 6:03:31 PM] ~ سبحان الله وبحمده سبحان الله العظيم: إلى جميع المواطنين ﺻﺪﺭ ﻋﻦ وزاره الداخليه المصريهﺍﻟﺒﻴﺎﻥ ﺍﻟﺘﺎﻟﻲ
[22/05/2023, 2:56:39 PM] ~ ربي ابعد عني الحاقدين: لوبعتها 8ج اتلام 8ج البكته

When I tried using the abridged version of the problematic message on its own, it produced the same error:
[23/05/2023, 6:03:31 PM] ~ سبحان الله وبحمده سبحان الله العظيم: إلى جميع المواطنين ﺻﺪﺭ ﻋﻦ وزاره الداخليه المصريهﺍﻟﺒﻴﺎﻥ ﺍﻟﺘﺎﻟﻲ
```

The code seems to run, but I'm unsure if the result is as desired.

Could you assist me in trying to understand the structure of each message? That is, I can see that it starts with `[day/month/year, hour:minute:second *M] ~`, but then it is unclear to me what follows. What is the username and message text part? Could you point to these for the sample that you shared above?

Thanks!
