### ISSUE TITLE
"None of [Index(['date', 'username', 'message'], dtype='object')] are in the [columns]"

### ISSUE THREAD

**Issue by Somtochukwu-Achikanu** [lucasrodes/whatstk#142]
The following code

```python
from whatstk import WhatsAppChat
import pandas as pd
chats = WhatsAppChat.from_source(filepath='/content/_chat.txt', hformat='%d/%m/%Y, %I:%M%p-%name :').df
```

leads to error: `KeyError: "None of [Index(['date', 'username', 'message'], dtype='object')] are in the [columns]"`

The content of `/content/_chat.txt` is:
```
[11/12/2019, 14:54:43] Pastor Uba: https://youtu.be/UDAcGn2SL6A
[11/12/2019, 15:11:43] Joshua Onyebuchi: The link to this sir?
```

**Comment by lucasrodes** [comment]
thanks for reporting, @Somtochukwu-Achikanu.

I'll look into this in the upcoming weeks.

**Comment by lucasrodes** [comment]
Hi @Somtochukwu-Achikanu, thanks for using this library. Based on your chat text, your call to `from_source` is not using the appropriate `hformat` value. Please read how to use this header [in the documentation](https://whatstk.readthedocs.io/en/stable/source/getting_started/hformat.html).

In your case, the appropriate value should be `hformat="[%m/%d/%y, %H:%M:%S] %name:"`:

```python
from whatstk import WhatsAppChat
chats = WhatsAppChat.from_source(filepath='/content/_chat.txt', hformat="[%m/%d/%y, %H:%M:%S] %name:").df
```

Additional notes:

- That most of the times, the header of your chat is _automatically_ detected, so you don't need to specify it.
- You can use the `df_from_txt_whatsapp` function instead, as you can [read in the docs](https://whatstk.readthedocs.io/en/stable/source/about.html#first-contact-with-whatstk)

```python
from whatstk import df_from_txt_whatsapp
df = df_from_txt_whatsapp("/content/_chat.txt")
```

**Comment by Somtochukwu-Achikanu** [comment]
Thank you for the reply but its still throwing more errors about the month and not sure what to do about that...

The error:
``
ValueError                                Traceback (most recent call last)
[<ipython-input-4-ab4494d8ceb8>](https://localhost:8080/#) in <cell line: 3>()
      1 from whatstk import WhatsAppChat
      2 from whatstk import df_from_txt_whatsapp
----> 3 df = df_from_txt_whatsapp("/content/_chat.txt", hformat= "[%m/%d/%y, %H:%M:%S] %name:")
      4 print(df.head())

3 frames
[/usr/local/lib/python3.10/dist-packages/whatstk/whatsapp/parser.py](https://localhost:8080/#) in _parse_line(text, headers, i)
    269         )
    270     else:
--> 271         date = datetime(
    272             year,
    273             int(result_["month"]),

ValueError: month must be in 1..12 ``
