### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by reinaldogani** [lucasrodes/whatstk#17]
I can't seem to parse my whatsapp txt file
Format is [MM/DD/YYYY hh:mm:ss PM] - username: message

Do you have solution for this?
Your help is much appreciated
![screen shot 2018-01-29 at 18 53 18](https://user-images.githubusercontent.com/35919847/35506936-0899d9ce-0526-11e8-9f7d-47d31820fdc2.png)

**Comment by lucasrodes** [comment]
Can you please provide me with an example of the chat format?

From your comment, I understood it was something like the following. Can you please verify this? I am getting a different error.

```
04/15/2016 13:19:20 PM - Person1: hello
04/15/2016 13:20:20 PM - Person2: hi
04/15/2016 13:21:20 PM - Person1: how are you
```

**Comment by reinaldogani** [comment]
Mine has [] outside the timestamp. I attach the screenshot below. I am using Bahasa Indonesia as medium of group chat. Do you know if there is any way that whatsapp can change exported timestamp format?

![screen shot 2018-01-30 at 00 11 12](https://user-images.githubusercontent.com/35919847/35520692-b5e4bc4e-0552-11e8-8d55-17511f73f37f.png)

**Comment by lucasrodes** [comment]
Thanks for your message. I was not aware of this kind of format. I will update the code to support this format. I will let you know! ;)

**Comment by lucasrodes** [comment]
@reinaldogani I have updated the code, please clone again. To import your chat please use:

```python
import whatstk.parser as wp
import whatstk.vis as wv
chat = wp.WhatsAppChat("Users/reinaldogani/Desktop/family.txt", date_format='mdy')
```

Note that I have added a new argument (`date_format`) which is defines the date format of your header. Namely, your chatlog uses `MM.DD.YYYY`, hence 'mdy' (m: month, d: day, y:year).
Please let me know how it goes!

I am planning to upload clearer documentation on this project in the near future.

**Comment by reinaldogani** [comment]
@lucasrodes Thank you for the fix! I try again, but I get an error as can be seen in the picture below.
![screen shot 2018-01-30 at 22 27 43](https://user-images.githubusercontent.com/35919847/35571363-de86e748-060c-11e8-96f2-d65b6c257bed.png)

**Comment by lucasrodes** [comment]
@reinaldogani, you are importing `WhatsAppChat` wrong. Try append the folder containing the library `whatstk` instead of the library. 

```python
import sys
sys.path.append('/Users/reinaldogani/Desktop')
```
Then simply import the parser as

```python
import whatstk.parser as wp
```

**Comment by reinaldogani** [comment]
@lucasrodes - it is working perfectly. Thank you!

**Comment by lucasrodes** [comment]
Nice, glad to hear that!
