### ISSUE TITLE
response_matrix

### ISSUE THREAD

**Issue by kafran** [lucasrodes/whatstk#20]
Why some functions like response_matrix are gone?

**Comment by lucasrodes** [comment]
Thanks for your message @kafran . I realised some methods got lost while merging the develop and master branches. You can find these here: https://github.com/lucasrodes/whatstk/blob/86beb606a2bef2db5ee2f0cd2fc8bf895f3a01a4/whatstk/parser.py

However, this should be re-introduced. Thus I have labeled this thread as 'enhancement'.

**Comment by kafran** [comment]
I restored the methods to the develop branch. I'm totally new to git. I hope to have it done correctly.
