### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by emanuel030** [lucasrodes/whatstk#24]
I receive this  `AttributeError` when using the sample chats, both dash and dot: 
```
~/coding/whatstk/whatstk/parser.py in _get_date_component(header, pattern, offset)
    155     py = re.compile(pattern)
    156     match_0 = py.match(header[offset:])
--> 157     component = int(match_0.group()[:-1])
    158     component_end = match_0.end() + offset
    159     return component, component_end

AttributeError: 'NoneType' object has no attribute 'group'
```
Also I'm not able to open the `whatstkenv` kernel in the jupyter notebook. are those two related?
I have tried to modify the `get_date_component` function but couldn't get rid of the Error.

**Comment by kafran** [comment]
I think I know what is this about. I will look into it.

**Comment by kafran** [comment]
As I'm pretty new to python and git, I made a pull request into develop branch. I will wait for @lucasrodes to review. You could try it from develop branch to see if it fix the error for you.

**Comment by lucasrodes** [comment]
Closed due to inactivity
