### ISSUE TITLE
Work on whatstk logo, center-align text in README.md

### ISSUE THREAD

**Issue by albertaparicio** [lucasrodes/whatstk#44]
We want to have the title and badges centered, like it has been done in https://github.com/semantic-release/semantic-release/blob/master/README.md

**Comment by lucasrodes** [comment]
- We may want to re-think the README.md file. Currently it might be too crowded.
- Better explain steps: (1) export chat in phone (add GIFs), (2) use library simple example

**Comment by lucasrodes** [comment]
Issue has been now moved to more general issue #46
