### ISSUE TITLE
Rethink README.md

### ISSUE THREAD

**Issue by lucasrodes** [lucasrodes/whatstk#46]
Currently the README.md file is a bit crowded. We might want to simplify and better structure it.

### 1. Titles
- [X] Add title, subtitle.
- [X] Center titles and badges (example https://github.com/semantic-release/semantic-release/blob/master/README.md)
- [X] Add logo

### 2. Getting Started section
- [X] Reduce amount of verbose and simplify examples. Move more specific examples to other file (e.g. docs/examples.md)
- [x] Add chat exporting *mini-tutorial* details. Example in http://github.com/lucasrodes/whatstk-gui/.

### 3. Other sections
- [X] Add "Documentation" link in TOC
- [X] Remove "Known Issues"
- [x] List contributors

**Comment by albertaparicio** [comment]
It would be interesting to link the docs in the README Table of Contents

**Comment by lucasrodes** [comment]
Changing assignee due to inactivity.

Working on branch feature/documentation

**Comment by lucasrodes** [comment]
Logo added in commit [6f90a543853f491b97ec059d1be313bacc911de9](https://github.com/lucasrodes/whatstk/tree/6f90a543853f491b97ec059d1be313bacc911de9). Designed by Clara Sáez Calabuig, contribution to the project (to be listed as contributor).
