### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by lucasrodes** [lucasrodes/whatstk#7]
List of detected possible header formats (those ticked are currently supported):

- [x] DD.MM.YYYY, hh:mm - username:
- [x] DD.MM.YYYY, hh:mm: username:
- [x] DD.MM.YYYY, hh:mm PM - username:
- [x] DD.MM.YYYY, hh:mm PM: username:
- [x] DD.MM.YYYY, hh:mm:ss - username:
- [x] DD.MM.YYYY, hh:mm:ss: username:
- [x] DD.MM.YYYY, hh:mm:ss PM - username:
- [x] DD.MM.YYYY, hh:mm:ss PM: username:
- [x] DD/MM/YYYY, hh:mm - username:
- [x] DD/MM/YYYY, hh:mm: username:
- [x] DD/MM/YYYY, hh:mm PM - username:
- [x] DD/MM/YYYY, hh:mm PM: username:
- [x] DD/MM/YYYY, hh:mm:ss - username:
- [x] DD/MM/YYYY, hh:mm:ss: username:
- [x] DD/MM/YYYY, hh:mm:ss PM - username:
- [x] DD/MM/YYYY, hh:mm:ss PM: username:
- [x] DD-MM-YYYY, hh:mm - username:
- [x] DD-MM-YYYY, hh:mm: username:
- [x] DD-MM-YYYY, hh:mm PM - username:
- [x] DD-MM-YYYY, hh:mm PM: username:
- [x] DD-MM-YYYY, hh:mm:ss - username:
- [x] DD-MM-YYYY, hh:mm:ss: username:
- [x] DD-MM-YYYY, hh:mm:ss PM - username:
- [x] DD-MM-YYYY, hh:mm:ss PM: username:
- [ ] MM.DD.YYYY, hh:mm - username:
- [ ] MM.DD.YYYY, hh:mm: username:
- [ ] MM.DD.YYYY, hh:mm PM - username:
- [ ] MM.DD.YYYY, hh:mm PM: username:
- [ ] MM.DD.YYYY, hh:mm:ss - username:
- [ ] MM.DD.YYYY, hh:mm:ss: username:
- [ ] MM.DD.YYYY, hh:mm:ss PM - username:
- [ ] MM.DD.YYYY, hh:mm:ss PM: username:
- [ ] MM/DD/YYYY, hh:mm - username:
- [ ] MM/DD/YYYY, hh:mm: username:
- [ ] MM/DD/YYYY, hh:mm PM - username:
- [ ] MM/DD/YYYY, hh:mm PM: username:
- [ ] MM/DD/YYYY, hh:mm:ss - username:
- [ ] MM/DD/YYYY, hh:mm:ss: username:
- [ ] MM/DD/YYYY, hh:mm:ss PM - username:
- [ ] MM/DD/YYYY, hh:mm:ss PM: username:
- [ ] MM-DD-YYYY, hh:mm - username:
- [ ] MM-DD-YYYY, hh:mm: username:
- [ ] MM-DD-YYYY, hh:mm:ss - username:
- [ ] MM-DD-YYYY, hh:mm:ss: username:
- [ ] MM-DD-YYYY, hh:mm:ss PM - username:
- [ ] MM-DD-YYYY, hh:mm:ss PM: username:
- [ ] MM-DD-YYYY, hh:mm:ss PM - username:
- [ ] MM-DD-YYYY, hh:mm:ss PM: username:
- [x] [MM-DD-YYYY, hh:mm:ss PM] username:

If you are having problems, please comment with your chat 'header'

PD: Possibly implement an algorithm that can detect the header pattern by itself in an unsupervised manner.

**Comment by lucasrodes** [comment]
Got you @emanuel030, thanks for reporting. I will try to have support for this within this month. In the meantime, if you need it asap, you should be able to define your own regex for your headers using arguments `regex` and `regex_alert` in `WhatsAppChat` class.

We are currently discussing how to provide extensive support to all formats, since it seems there are endless header formats.

**Comment by kafran** [comment]
@emanuel030 is this the message header or a copy and past? For example, this is an export from my phone:

<pre>
6/28/16, 15:53 - ‪+55 00 0000-0000: [10/6 11:31] ‪+55 11 1111-1111‬: Vixe, consegui com nosso colega Luiz, uma cartilha do MEC q não autoriza diárias para estudante.
[10/6 11:32] ‪+55 22 2222-2222: Aqui viaja..  internacional também... nas só passagem, sem diárias. Recebem uma ajuda de custo pelo órgão
[10/6 11:51] ‪+55 33 3333-3333: ALUNO = AJUDA DE CUSTO, independente da origem do recurso
[10/6 11:56] ‪+55 44 4444-4444: Aluno vai pelo auxílio viagem
</pre>

Where the user `+55 00 0000-0000` copied and pasted messages from `+55 22 2222-2222`, `+55 33 3333-3333` and `‪+55 44 4444-4444`. Tha's why considering [] brackets as part of the header is not a good choice in my case, because in the example above, its all part of the same message, which is a copy and past.

I hope I have made myself understood.

**Comment by emanuel030** [comment]
This would be a copy from the chat itself: 
```
[20.09.17, 16:54:32] Veronica MBS: Hey guys!
[20.09.17, 16:54:43] Veronica MBS: I just created 
```

**Comment by kafran** [comment]
@emanuel030 Can you do a copy and past in that chat? For example, select these two messages and past it on that chat, and export it? =)

**Comment by emanuel030** [comment]
@kafran The header does not change in my case if you copy a text, also does not change if you reply to one of the previous chats. It is still:
```
[17.04.18, 21:06:52] Jack: Sorry mlad but im home and hosed
[20.04.18, 16:17:52] emanuel: Sorry mlad but im home and hosed
```

**Comment by kafran** [comment]
I would like to propose you guys to join this group about whatstk so we can generate the same chat and export from multiples devices and languages and timezones and understand how Whatsapp construct these files, as it seems to be a mystery: https://chat.whatsapp.com/LBR8ZMZWc57JZ1RKTNRKVa

What do you think? @lucasrodes @albertaparicio @emanuel030

**Comment by lucasrodes** [comment]
Issue closed because now the header format can be manually set (see `WhatsAppChat` arguments)
